# Configuration Settings for ZED-F9P device including RTK over NTRIP - RTCM

debug: 1                    # Range 0-4 (0 means no debug statements will print)

device: /dev/ttyACM0
frame_id: gps0

uart1:
  baudrate: 115200           # 
  in: 16                    # RTCM 3
  out: 16                    # No UART out for rover

fix_mode: auto
enable_ppp: false           # Not supported by C94-M8P
dr_limit: 0

# Enable u-blox message publishers
publish:
  all: false
  nav:
    all: true
    relposned: true
    posllh: true
    posecef: true
  rxm:
    rtcm: true

dgnss_mode: 1               # Fixed mode

inf: 
  all: true                   # Whether to display all INF messages in console
